services:
  redis:
    image: redis:alpine
    container_name: hls-transocder-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
  
  redis-commander:
    container_name: hls-transocder-redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped
  
  asynqmon:
    image: hibiken/asynqmon
    container_name: hls-transocder-asynqmon
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped